import {
    SiJavascript,
    SiTypescript,
    SiNodedotjs,
    SiReact,
    SiGit,
    SiGithub,
    SiNextdotjs,
    SiCypress,
    SiJest,
    SiSass,
    SiHtml5,
    SiCss3,
    SiDocker,
    SiVite,
    SiPostgresql,
    SiSupabase,
    SiFigma,
    SiTailwindcss,
  } from 'react-icons/si';
  
  import { FaEnvelope, FaWhatsapp, FaLinkedin, FaGithub, FaInstagram, FaJava } from 'react-icons/fa';
  
  export const icons = {
    SiJavascript,
    SiTypescript,
    SiNodedotjs,
    SiReact,
    SiGit,
    SiGithub,
    SiNextdotjs,
    SiCypress,
    SiJest,
    SiSass,
    SiHtml5,
    SiCss3,
    SiDocker,
    SiVite,
    SiPostgresql,
    SiSupabase,
    SiFigma,
    SiTailwindcss,
    FaEnvelope,
    FaWhatsapp,
    FaLinkedin,
    FaGithub,
    FaInstagram,
    FaJava
  };